baseURL = 'http://jamiemcquire23.github.io/'
languageCode = 'en-us'
title = 'Jamie McQuire'
theme = 'hugo-researcher'
math = true
disableKinds = ["taxonomy", "term"]

# Site Parameters
[params]
  name = "Jamie McQuire"
  description = "Data Scientist | PhD Computer Science | ex-Expedia"
  email = "jamiemcquire23@gmail.com"
  phone = "+1 (559) 779-2066"
  address = "Sacramento, California, United States of America"
  [params.footer]
    text = "Made with Hugo"
    url = "https://github.com/gohugoio/hugo"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:jamiemcquire23@gmail.com"
  [[params.socialIcons]]
    icon = "ai ai-google-scholar"
    title = "Scholar"
    url = "https://scholar.google.com/citations?user=t_TC_vYAAAAJ&hl=en&oi=ao"

# Social Links
[params.social]
  github = "https://github.com/JamieMcQurie23"
  linkedin = "https://www.linkedin.com/in/jamie-mcquire-a102b0163/"
  googleScholar = "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AL3_zihE7uqkkUt5ljphUUx3_iYcTv68QWnL340OMBjIxQTpM5WI9EsFlT7ONiHQcASVIY7ajpLSSLfliIFglw&user=t_TC_vYAAAAJ"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    style = "github"  # Or your preferred theme

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3